// <auto-generated />
using CheckList.Infrastructure.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CheckList.Migrations
{
    [DbContext(typeof(ChecklistDbContext))]
    [Migration("20240420160050_IniciandoDBComExemplos")]
    partial class IniciandoDBComExemplos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CheckList.Models.Entities.TarefaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("StatusConcluido")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Tarefa");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Exemplo de tarefa concluída",
                            StatusConcluido = true
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Exemplo de tarefa a fazer",
                            StatusConcluido = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
